# Generated by Django 5.0.2 on 2024-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_techitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techitem',
            name='category',
            field=models.CharField(choices=[('tv', 'TV'), ('pc', 'PC'), ('laptop', 'Laptop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('other', 'Other')], max_length=100),
        ),
    ]
