# Generated by Django 5.0.2 on 2024-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_techitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techitem',
            name='category',
            field=models.CharField(choices=[('tv', 'tv'), ('computer', 'computer'), ('laptop', 'laptop'), ('phone', 'phone'), ('tablet', 'tablet'), ('other', 'other')], max_length=100),
        ),
    ]
