# Generated by Django 5.0.2 on 2024-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_techitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=220),
        ),
    ]
