# Generated by Django 5.0.2 on 2024-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_techitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techitem',
            name='image_url',
            field=models.URLField(),
        ),
    ]
