# Generated by Django 5.0.2 on 2024-07-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_techitem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='techitem',
            name='category',
            field=models.CharField(choices=[('tv', 'TV'), ('computer', 'Computer'), ('laptop', 'Laptop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('other', 'Other')], max_length=100),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cart')),
                ('tech_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.techitem')),
            ],
        ),
    ]
